gText_Birch_Welcome:: @ 82C897B
	.string "Hullo! We're about to arrive...\n"
	.string "OK!\p"
	
	.string "Soon we'll be in Breeze Town!\p"
	
	.string "I am Professor Baro.\n"
	.string "I was your friend since we\l"
	.string "lived in Kanto.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "You'll see new Pokémon in Corna.\p"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "Like this funky Plug-Oink!\n"
	.string "It's so cool!\p"
	
	.string "People often live with Pokémon,\n"
	.string "y'know...\p"
	
	.string "Sometimes they are lovely pets...\n"
	.string "But sometimes we use them\l"
	.string "for battle!\p"
	
	.string "Hey! But always between friends!\n"
	.string "You should never get angry, OK?\p"
	
	.string "There are some mysteries\n"
	.string "around Pokémon:\l"
	.string "Peace, chaos, order...\p"
	
	.string "They are things that are\n"
	.string "around uncovered Pokémon...\p"
	
	.string "Oh! I shouldn't forget!\p"
	
	.string "I want to give you a Pokémon\n"
	.string "in Breeze Town...\p"
	
	.string "Well, I'll tell you later...\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "Well... I...$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy or a girl,\n"
	.string "dude?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "Sure!\n"
	.string "And your name is..?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "{PLAYER}? Isn't it?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "The truck stopped...\p"
	
	.string "That means we've arrived\n"
	.string "to Breeze Town!\p"
	
	.string "Well, let's go!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "Hey you!\p"
	
	.string "When arrive home,\n"
	.string "help your mother with\l"
	.string "the moving.\p"
	
	.string "Then look out for me in my lab,\n"
	.string "Oh! Maybe I'm not in...\l"
	.string "I'm hearing from here\l"
	.string "an interesting Pokémon cry!\l"
	.string "Ja, Ja!\p"
	
	.string "OK, so are you ready, uh?\p"
	
	.string "New Pokémon are waiting for you!\p"
	.string "$"
